const constant = {
    REDIS_PREFIX_ACCESS_TOKEN: 'ACCESS_TOKEN',
    REDIS_PREFIX_PERMISSION: 'PERMISSION',
    REDIS_ADDRESS_PLC_CACHE: 'REDIS_ADDRESS_PLC_CACHE',
    PLC_CONFIG_CACHE: 'PLC_CONFIG_CACHE',
    SENSOR_CACHE: 'SENSOR_CACHE',
    STREAM_CONFIG_CACHE: 'STREAM_CONFIG_CACHE',
    STREAM_CACHE: 'STREAM_CACHE',
    DEVICE_CACHE: 'REDIS_DEVICE_CACHE',
    TAG_VALUE_CACHE: 'REDIS_TAG_VALUE_CACHE',
    CONTROL_VALUE_CHARGE: 'charge',
    CONTROL_VALUE_DIS_CHARGE: 'discharge',
}

module.exports = constant
