const express = require('express')
const router = express.Router()

const userRoute = require('./userRoute')
const authRoute = require('./authRoute')
const roleRoute = require('./roleRoute')
const valueRoute = require('./valueRoute')
const controlRoute = require('./controlRoute')
const deviceRoute = require('./deviceRoute')
const controlHistoryRoute = require('./controlHistoryRoute')
const reportRoute = require('./reportRoute')
const tagNameRoute = require('./tagNameRoute')
const configFtpRoute = require('./configFtpRoute')
const alarmRoute = require('./alarmRoute')
const configControlRoute = require('./configControlRoute')

router.use('/user', userRoute)
router.use('/auth', authRoute)
router.use('/role', roleRoute)
router.use('/value', valueRoute)
router.use('/device', deviceRoute)
router.use('/control', controlRoute)
router.use('/controlHistory', controlHistoryRoute)
router.use('/report', reportRoute)
router.use('/tagname', tagNameRoute)
router.use('/configFtp', configFtpRoute)
router.use('/alarm', alarmRoute)
router.use('/configControl', configControlRoute)

module.exports = router
