const { logger } = require('../config/loggerConfig')
const TagnameModel = require('../models/tagname')

async function tagnameSeeder() {
    await TagnameModel.deleteMany({})
    await TagnameModel.insertMany([
        //ADDRESS WORKING
        {
            name: 'bessVoltage',
            symbol: 'BESS Voltage',
            functionCode: 4,
            address: 100,
            dataType: 6,
            unit: 'V',
            offset: 0,
            gain: 1,
            deviceId: '684bcaeb7cac1b319680bf0a',
            isSaveDb: true,
            isSendFtp: false,
            note: 'BESS voltage',
            isOverviewVisible: true,
        },
        {
            name: 'bessCurrent',
            symbol: 'BESS Current',
            functionCode: 4,
            address: 102,
            dataType: 6,
            unit: 'A',
            offset: 0,
            gain: 1,
            deviceId: '684bcaeb7cac1b319680bf0a',
            isSaveDb: true,
            isSendFtp: false,
            note: 'BESS current',
            isOverviewVisible: false,
        },
        {
            name: 'bessPower',
            symbol: 'BESS Power',
            functionCode: 4,
            address: 104,
            dataType: 6,
            unit: 'kW',
            offset: 0,
            gain: 0.1,
            deviceId: '684bcaeb7cac1b319680bf0a',
            isSaveDb: true,
            isSendFtp: false,
            note: 'BESS power',
            isOverviewVisible: true,
        },
        {
            name: 'bessSoc',
            symbol: 'BESS SOC',
            functionCode: 4,
            address: 106,
            dataType: 2,
            unit: '%',
            offset: 0,
            gain: 1,
            deviceId: '684bcaeb7cac1b319680bf0a',
            isSaveDb: true,
            isSendFtp: false,
            note: 'BESS state of charge',
            isOverviewVisible: true,
        },
        {
            name: 'bessTemperature',
            symbol: 'BESS Temperature',
            functionCode: 4,
            address: 108,
            dataType: 2,
            unit: 'C',
            offset: 0,
            gain: 0.1,
            deviceId: '684bcaeb7cac1b319680bf0a',
            isSaveDb: true,
            isSendFtp: false,
            note: 'BESS temperature',
            isOverviewVisible: true,
        },

        // Gateway - deviceId: 684bcaeb7cac1b319680bf0b
        {
            name: 'gatewayVoltage',
            symbol: 'Gateway Voltage',
            functionCode: 4,
            address: 200,
            dataType: 6,
            unit: 'V',
            offset: 0,
            gain: 1,
            deviceId: '684bcaeb7cac1b319680bf0b',
            isSaveDb: true,
            isSendFtp: false,
            note: 'Gateway voltage',
            isOverviewVisible: true,
        },
        {
            name: 'gatewayCurrent',
            symbol: 'Gateway Current',
            functionCode: 4,
            address: 202,
            dataType: 6,
            unit: 'A',
            offset: 0,
            gain: 1,
            deviceId: '684bcaeb7cac1b319680bf0b',
            isSaveDb: true,
            isSendFtp: false,
            note: 'Gateway current',
            isOverviewVisible: true,
        },
        {
            name: 'gatewayPower',
            symbol: 'Gateway Power',
            functionCode: 4,
            address: 204,
            dataType: 6,
            unit: 'kW',
            offset: 0,
            gain: 0.1,
            deviceId: '684bcaeb7cac1b319680bf0b',
            isSaveDb: true,
            isSendFtp: false,
            note: 'Gateway power',
            isOverviewVisible: true,
        },
        {
            name: 'gatewayFrequency',
            symbol: 'Gateway Frequency',
            functionCode: 4,
            address: 206,
            dataType: 6,
            unit: 'Hz',
            offset: 0,
            gain: 0.01,
            deviceId: '684bcaeb7cac1b319680bf0b',
            isSaveDb: true,
            isSendFtp: false,
            note: 'Gateway frequency',
            isOverviewVisible: false,
        },
        {
            name: 'gatewayPowerFactor',
            symbol: 'Gateway Power Factor',
            functionCode: 4,
            address: 208,
            dataType: 6,
            unit: '',
            offset: 0,
            gain: 0.001,
            deviceId: '684bcaeb7cac1b319680bf0b',
            isSaveDb: true,
            isSendFtp: false,
            note: 'Gateway power factor',
            isOverviewVisible: true,
        },

        // Meter - deviceId: 684bcaeb7cac1b319680bf0c
        {
            name: 'meterVoltage',
            symbol: 'Meter Voltage',
            functionCode: 4,
            address: 300,
            dataType: 6,
            unit: 'V',
            offset: 0,
            gain: 1,
            deviceId: '684bcaeb7cac1b319680bf0c',
            isSaveDb: true,
            isSendFtp: false,
            note: 'Meter voltage',
            isOverviewVisible: true,
        },
        {
            name: 'meterCurrent',
            symbol: 'Meter Current',
            functionCode: 4,
            address: 302,
            dataType: 6,
            unit: 'A',
            offset: 0,
            gain: 1,
            deviceId: '684bcaeb7cac1b319680bf0c',
            isSaveDb: true,
            isSendFtp: false,
            note: 'Meter current',
            isOverviewVisible: true,
        },
        {
            name: 'meterActivePower',
            symbol: 'Meter Active Power',
            functionCode: 4,
            address: 304,
            dataType: 6,
            unit: 'kW',
            offset: 0,
            gain: 0.1,
            deviceId: '684bcaeb7cac1b319680bf0c',
            isSaveDb: true,
            isSendFtp: false,
            note: 'Meter active power',
            isOverviewVisible: true,
        },
        {
            name: 'meterEnergyImport',
            symbol: 'Meter Energy Import',
            functionCode: 4,
            address: 306,
            dataType: 6,
            unit: 'kWh',
            offset: 0,
            gain: 0.001,
            deviceId: '684bcaeb7cac1b319680bf0c',
            isSaveDb: true,
            isSendFtp: false,
            note: 'Meter import energy',
            isOverviewVisible: true,
        },
        {
            name: 'meterEnergyExport',
            symbol: 'Meter Energy Export',
            functionCode: 4,
            address: 308,
            dataType: 6,
            unit: 'kWh',
            offset: 0,
            gain: 0.001,
            deviceId: '684bcaeb7cac1b319680bf0c',
            isSaveDb: true,
            isSendFtp: false,
            note: 'Meter export energy',
            isOverviewVisible: false,
        },
    ])
        .then(() => {
            logger.info('Tagname Seeder Done')
        })
        .catch((err) => {
            logger.error('Tagname Seeder Failed', err)
        })
}

module.exports = tagnameSeeder



